export const RECEIVE_BOTS = 'RECEIVE_BOTS'
export const ADD_NEW_BOT = 'ADD_NEW_BOT'
export const CHANGE_STATE_TO_STOP = 'CHANGE_STATE_TO_STOP'
export const CHANGE_STATE_TO_START = 'CHANGE_STATE_TO_START'
export const DETELE_BOT = 'DELETE_BOT'
export const RENAME_BOT = 'RENAME_BOT'
export const RECEIVE_BOT = 'RECEIVE_BOT'

export const RECEIVE_TEMPLATES = 'RECEIVE_TEMPLATES'
export const ADD_NEW_TEMPALTE = 'ADD_NEW_TEMPLATE'

export const LOG_IN = 'LOG_IN'
export const LOG_IN_ERROR = 'LOG_IN_ERROR'
export const RESET_STATE = 'RESET_STATE'

export const MARKETPLACE_ADDNEWBOT = 'MARKETPLACE_ADDNEWBOT'
export const MARKETPLACE_RECEIVEBOT = 'MARKETPLACE_RECEIVEBOT'
export const MARKETPLACE_DELETEBOT = 'MARKETPLACE_DELETEBOT'
