language: node_js
cache:
  yarn: true
  directories:
    - botconfig-frontend/node_modules
node_js:
  - "10"

script:
  - cd botconfig-frontend/
  - yarn
  - yarn build-demo

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: botconfig-frontend/dist/
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master